### ISSUE TITLE
data download problem

### ISSUE THREAD

**Issue by l11x0m7** [airKlizz/passage-ordering#1]
Hello,
it seems the VIST data download link is invalid.
I would really appreciate it if you can update the link as I really need this data.

Thanks

**Comment by airKlizz** [comment]
Hello, actually I was able to download the VIST data using the link in the README: https://drive.google.com/uc?id=1Arc5vnthfeg6qEHpKU_--y6MKZd5DM78 . Could you please try again and let me know if this still does not work.

**Comment by l11x0m7** [comment]
Yes, now it's available and thanks~
